CMake for building the support library
dropbox/djinni pull request #248
Opened 2016-07-04 15:38 UTC by mknejp

This is still a work in progress and here mainly for feedback.

I have added a `CMakeLists.txt` that allows bulding the support-lib with CMake. The target name is `djinni` and it comes with a few options:
- `DJINNI_WITH_OBJC` adds the Objective-C support files to the target
- `DJINNI_WITH_JNI` adds the JNI support files to the target
- `DJINNI_FRAMEWORK` builds the library as a `.framework` on Apple systems

There is nothing stopping you from having a single djinni library that contains both language support bindings if you're doing desktop work. I have also forced the target to be `SHARED` to make sure the `JNI_OnLoad` and `JNI_OnUnload` entry points are present. This has led to confusion in the past.

There is also the alternative of creating two separate targets `djinni-jni` and `djinni-objc` where users have to specify which one to link against. That is basically the main reason for this feedback as I'm quite undecided on which is better.

Because the `CXX_STANDARD` property cannot be propagated to consuming targets it needs to be set to >= `11` manually there.

I have not yet integrated the test suite or generator into CMake.

Note this includes the changes of #247 for now but that will be sorted out later.

2016-07-04 15:38 UTC, smarx commented
*Automated message from Dropbox CLA bot*

@mknejp, it looks like you've already signed the Dropbox CLA. Thanks!

2016-07-27 01:37 UTC, artwyman commented
Since they're mixed, this will need to wait to be resolved/merged until after #247.

This seems like a good idea, but since I don't use CMake myself, I can't really review it in detail.  I'd welcome comments from others in the community who do use CMake.  Lacking that, I'm relatively willing to merge whatever works for you, then accept further PRs if others try it out and suggest changes.

It doesn't look like the new CMake project for the support-lib is actually being referenced by the existing CMakeLists.txt files for the example or test suite.  Am I misinterpreting that?  It would be valuable for the new file to actually be used by something buildable out of the Djinni repo.  Otherwise there will be nothing to ensure they don't break with future changes.

2016-07-27 02:14 UTC, mknejp commented
> It doesn't look like the new CMake project for the support-lib is actually being referenced by the existing CMakeLists.txt files for the example or test suite.

That's right. My priority was to get the support lib exposed to users first, then worry about adding the test suite later.

2016-07-27 03:05 UTC, artwyman commented
I'd encourage you to go ahead and add some test coverage, lest it break constantly.
Since it's a new file with no impact on existing users, though, I'm okay with merging it for people to try out (once #247 is resolved), even without test coverage.

2016-08-29 13:41 UTC, 4brunu commented
I have tested this and it works :)
@mknejp @artwyman what do you guys think of making this PR independent of https://github.com/dropbox/djinni/pull/247?
Because the pending PR (https://github.com/dropbox/djinni/pull/247) seems to be a complicated and long process until it get's merged, and this PR is simple but extremely useful :)
If you want I can try to help tweak the CMakeLists.txt to work with the current Djinni configuration.

2016-08-29 21:35 UTC, artwyman commented
Decoupling PRs is a good idea in my book.

2016-09-19 10:30 UTC, 4brunu commented
@mknejp Is it ok to you that I create a PR with the CMakeLists.txt modified to the current djinni structure, or do you want to do that?

2016-09-26 05:45 UTC, jesperrix commented
What are the status of this one? I think it could be really usefull to build the supportlib with CMake.

2016-09-26 08:39 UTC, 4brunu commented
I think this PR is pending the approval of https://github.com/dropbox/djinni/pull/281.
I have managed to create a simpler CMake integration to the current djinni structure, without the Framework support for iOS.
I'm not sure if I should create a PR with it, or wait for the pending PR's.
@mknejp @artwyman What do you think?

2016-09-26 18:15 UTC, mknejp commented
I don't think the `install` target can be made code-compatible with source builds if #281 is not accepted first. Otherwise you'd have to change your code (or re-generate) based on whether you use Djinni directly form the repository or from pre-installed binaries/headers.

2016-10-10 14:05 UTC, mknejp commented
This has now been adjusted for the changes in #281.

2016-11-05 23:43 UTC, mknejp commented
Update: new option `DJINNI_STATIC_LIB`

2016-12-28 01:00 UTC, artwyman requested changes
Sending this back to resolve conflicts and update after #281 is fully resolved (hopefully soon).  I'll do another full review after that point.

2017-03-06 13:21 UTC, 4brunu commented
@mknejp I really would like to see this PR get merged, but it cannot be merged before https://github.com/dropbox/djinni/pull/281…
Any new on this?
If this will take too long to get merged, I would be willing to create a PR with CMake for building the support library with the current structure of djinni, or you could do it if you want, because you created the PR first :slightly_smiling_face:
Even if the CMake integration wouldn't support all the features that this PR support, it would be good to have an immediate solution, and this PR could be an improvement.
@mknejp @artwyman What do you think about this?
Thanks :slightly_smiling_face:

2017-06-10 03:24 UTC, artwyman commented
@4brunu if you want to send a separate PR for CMake support without the reorg, I'd be open to that, since it doesn't look like #281 is likely to be resolved quickly.

2017-06-10 11:25 UTC, mknejp commented
I think with #303 merged this isn't needed anymore. Unfortunately I haven't worked on a project that uses Djinni for quite a while now so I don't know if I ever get around to finishing this.

2025-09-01 09:29 UTC, closed without merging