Suppress -Wdirect-ivar-access in generated objcpp files
dropbox/djinni pull request #255
Opened 2016-07-15 14:15 UTC by mknejp

We just added djinni generated files to an existing iOS project and it blessed us with about 200 new warnings. This adds `#pragma clang diagnostic ignored "-Wdirect-ivar-access"` to `.mm` files unless someone knows how to generate equally efficient code that doesn't trigger it.

2016-07-15 14:15 UTC, smarx commented
*Automated message from Dropbox CLA bot*

@mknejp, it looks like you've already signed the Dropbox CLA. Thanks!

2016-07-27 03:39 UTC, artwyman commented
What build settings does the affected project have?  Is this warning turned on explicitly?
I haven't seen this warning, even though we run with -Werror -Wall -Wextra, and I don't even see an option to enable this warning in Xcode.  This change isn't really dangerous, and the fact that it's ObjC++ code overcomes most of my normal concerns about the compiler-specific pragma.  However I wonder whether non-default-enabled warnings should be better addressed by changing project/compile settings rather than modifying the generator.

2016-07-27 12:04 UTC, mknejp commented
The warning is turned on manually in a `.xcconfig` because of coding guidelines and the generated code is in the same project. Sure, the generated files could be put into a different project but that means more build settings, more dependencies, more maintenance overhead.

2016-07-27 22:36 UTC, artwyman commented
You can also add compile flags to individual files in a target in Xcode (though gyp can't do that).

Hmm, I'm torn.  It seems like there might be a slippery slope here, since we don't want the Djinni generator to have to be modified for lots of non-standard build flags which different people come up with.  I suspect a change like this might be hard to maintain and subject to accidental breakage by Djinni devs who don't run with this warning enabled, and miss a case when changing or refactoring code.

That being said, there's no risk of breaking anyone who doesn't have the flag enabled, so I can merge this.  Two requests before I do:

- Please add a comment in the generator code explaining why the pragma is there.
- Please wrap the pragma in #ifdef __clang__ just to avoid unknown pragma warnings in other compilers.  It's unclear if anyone compiles Objective-C in any other compiler, but it is technically possible (there's a GNU ObjcC compiler, apparently).

2016-11-05 22:24 UTC, mknejp commented
I almost forgot this was still open. Currently looking at this again. One thing though:
> Please wrap the pragma in #ifdef clang just to avoid unknown pragma warnings in other compilers. It's unclear if anyone compiles Objective-C in any other compiler, but it is technically possible (there's a GNU ObjcC compiler, apparently).

There's already `__has_feature(objc_arc)` in the generated files which is Clang-only so I'd say the compiler choice is pretty much set.

2016-12-22 12:21 UTC, steipete commented on src/source/ObjcppGenerator.scala
> +        w.wl("#pragma clang diagnostic ignored \"-Wdirect-ivar-access\"")
I would remove the `w.wl("#if __clang__")` `w.wl("#endif")` wrapping, else lgtm. We currently suppress the warning via an xcconfig file but having a more selective suppression would be really nice. Thanks for working on that!

2016-12-28 01:37 UTC, artwyman requested changes
Suggested changes inline.  The xcodeproj files also need merging with recent changes before this can be merged.

2016-12-28 01:37 UTC, artwyman commented on src/source/ObjcppGenerator.scala
> +		w.wl("#if __clang__")
Looks like the indentation of the new code here is mixing tabs and spaces.  Can you standardize on spaces to match the existing code, please?

2016-12-28 01:37 UTC, artwyman commented on src/source/ObjcppGenerator.scala
> +		w.wl("#endif")
The generated code doesn't include the #if/#endif here, so I presume it wasn't regenerated after the most recent change?  Please re-generate to reflect the latest state of the generator.  After seeing the commentary I'm fine with merging this either with or without the #if.

2025-09-01 09:29 UTC, closed without merging